version: '3.9'

services:
  # Servicio de la aplicación Go
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: servidor-monitoreo:latest
    container_name: backend-monitoreo
    ports:
      - "8080:8080"
    env_file:
      - .env.docker
    volumes:
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s
  # Servicio de PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: postgres-monitoreo
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=server_monitoring
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Servicio de Redis
  redis:
    image: redis:7-alpine
    container_name: redis-monitoreo
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  postgres_data:
  redis_data: 
